# Filesystems
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_ROOT_EXTRA_FOLDERS   := dsp efs firmware firmware-modem persist

# Partition sizes
BOARD_BOOTIMAGE_PARTITION_SIZE      := 33554432
BOARD_RECOVERYIMAGE_PARTITION_SIZE  := 33554432
BOARD_PERSISTIMAGE_PARTITION_SIZE   := 33554432
BOARD_FLASH_BLOCK_SIZE              := 131072
